# Generated by Django 2.0.6 on 2019-04-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front_panel', '0002_mysite_user_user_lastlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=225)),
                ('recipe_image', models.CharField(max_length=225, null=True)),
                ('recipe_description', models.CharField(default='', max_length=225)),
                ('recipe_isactive', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.category')),
                ('user_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User')),
            ],
        ),
    ]
