# Generated by Django 2.0.6 on 2019-05-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('front_panel', '0013_contacttable_contact_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExercise',
            fields=[
                ('add_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(default='', max_length=225)),
                ('exercise_image', models.CharField(default='', max_length=225)),
                ('exercise_discription', models.CharField(default='', max_length=225)),
                ('exercise_price', models.CharField(max_length=225, null=True)),
                ('exercise_isProcedure', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_category', models.CharField(default='', max_length=225, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe_procedure_tb',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=225)),
                ('procedure_discription', models.TextField(default='')),
                ('prep_time', models.CharField(max_length=225)),
                ('cook_time', models.CharField(max_length=225)),
                ('total_time', models.CharField(max_length=225)),
                ('procedure_ingredients', models.TextField(default='')),
                ('procedure_instructions', models.TextField(default='')),
                ('procedure_notes', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=225)),
                ('recipe_image', models.CharField(max_length=225, null=True)),
                ('recipe_description', models.CharField(default='', max_length=225)),
                ('recipe_procedure', models.TextField(default='')),
                ('recipe_isactive', models.BooleanField(default=True)),
                ('recipe_isProcedure', models.BooleanField(default=False)),
                ('recipe_price', models.CharField(max_length=225, null=True)),
                ('category_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.category')),
                ('user_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User')),
            ],
        ),
        migrations.AddField(
            model_name='recipe_procedure_tb',
            name='recipe_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.recipes'),
        ),
        migrations.AddField(
            model_name='recipe_procedure_tb',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User'),
        ),
        migrations.AddField(
            model_name='addexercise',
            name='exercise_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.ExerciseCategory'),
        ),
        migrations.AddField(
            model_name='addexercise',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User'),
        ),
    ]
