# Generated by Django 2.0.6 on 2019-05-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0013_contacttable_contact_time'),
        ('nutritionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure_exercise',
            fields=[
                ('ex_procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=225, null=True)),
                ('parts_included', models.CharField(max_length=225, null=True)),
                ('equipment_required', models.CharField(max_length=225, null=True)),
                ('steps_included', models.TextField(default='')),
                ('exercise_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.ExerciseCategory')),
                ('user_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User')),
            ],
        ),
    ]
