# Generated by Django 2.0.6 on 2019-04-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='user_name',
            new_name='user_email',
        ),
    ]
