# Generated by Django 2.0.6 on 2019-04-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0002_auto_20190403_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_procedure',
            field=models.TextField(default=''),
        ),
    ]
