# Generated by Django 2.0.6 on 2019-05-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0002_procedure_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure_exercise',
            old_name='exercise_id',
            new_name='add_exercise_id',
        ),
    ]
