# Generated by Django 2.0.6 on 2019-04-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0002_mysite_user_user_lastlogin'),
        ('nutritionist', '0003_recipes_recipe_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_procedure_tb',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=225)),
                ('procedure_discription', models.CharField(max_length=225)),
                ('prep_time', models.CharField(max_length=225)),
                ('cook_time', models.CharField(max_length=225)),
                ('total_time', models.CharField(max_length=225)),
                ('procedure_ingredients', models.CharField(max_length=225)),
                ('procedure_instructions', models.CharField(max_length=225)),
                ('procedure_notes', models.CharField(max_length=225)),
                ('recipe_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nutritionist.recipes')),
                ('user_email', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User')),
            ],
        ),
    ]
