# Generated by Django 2.0.6 on 2019-04-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionist', '0004_recipe_procedure_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_isProcedure',
            field=models.BooleanField(default=False),
        ),
    ]
