# Generated by Django 2.0.6 on 2019-04-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0002_mysite_user_user_lastlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_details',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.CharField(max_length=255)),
                ('logout_time', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
    ]
