# Generated by Django 2.0.6 on 2019-04-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0003_login_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysite_user',
            old_name='user_lastlogin',
            new_name='user_sign_up',
        ),
    ]
