# Generated by Django 2.0.6 on 2019-04-11 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0004_auto_20190411_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='user_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='front_panel.MySite_User'),
        ),
    ]
