# Generated by Django 2.0.6 on 2019-04-12 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0005_login_details_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_details',
            name='user_email',
        ),
    ]
