# Generated by Django 2.0.6 on 2019-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0007_auto_20190412_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
