# Generated by Django 2.0.6 on 2019-04-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0008_mysite_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysite_user',
            name='user_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
