# Generated by Django 2.0.6 on 2019-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0009_mysite_user_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('recipe', models.CharField(default='', max_length=255, null=True)),
                ('recipe_name', models.CharField(default='', max_length=225, null=True)),
                ('recipe_image', models.CharField(default='', max_length=225, null=True)),
                ('recipe_description', models.CharField(default='', max_length=225, null=True)),
                ('recipe_price', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryCartTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('recipe', models.CharField(default='', max_length=255, null=True)),
                ('recipe_name', models.CharField(default='', max_length=225, null=True)),
                ('recipe_image', models.CharField(default='', max_length=225, null=True)),
                ('recipe_description', models.CharField(default='', max_length=225, null=True)),
                ('recipe_price', models.CharField(max_length=225, null=True)),
            ],
        ),
    ]
