# Generated by Django 2.0.6 on 2019-05-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0010_saletable_temporarycarttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saletable',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.RenameField(
            model_name='temporarycarttable',
            old_name='recipe',
            new_name='recipe_id',
        ),
    ]
