# Generated by Django 2.0.6 on 2019-05-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0011_auto_20190506_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default='', max_length=225)),
                ('contact_email', models.CharField(default='', max_length=225)),
                ('contact_subject', models.CharField(default='', max_length=225, null=True)),
                ('contact_message', models.TextField(default='')),
            ],
        ),
    ]
