# Generated by Django 2.0.6 on 2019-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0012_contacttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttable',
            name='contact_time',
            field=models.CharField(default='', max_length=225),
        ),
    ]
