# Generated by Django 2.0.6 on 2019-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0013_contacttable_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarycarttable',
            name='recipe_procedure',
            field=models.TextField(default=''),
        ),
    ]
