# Generated by Django 2.0.6 on 2019-05-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0014_temporarycarttable_recipe_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletable',
            name='recipe_procedure',
            field=models.TextField(default=''),
        ),
    ]
