# Generated by Django 2.0.6 on 2019-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0015_saletable_recipe_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_pay', models.CharField(max_length=10000, null=True)),
                ('invoice', models.CharField(max_length=10000, null=True)),
                ('user_email', models.CharField(max_length=10000, null=True)),
                ('verify_pay', models.NullBooleanField(default=0)),
            ],
        ),
    ]
