# Generated by Django 2.0.6 on 2019-05-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0016_payment_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarycarttable',
            name='recipe_procedure',
        ),
        migrations.AddField(
            model_name='temporarycarttable',
            name='item_added',
            field=models.BooleanField(default=False),
        ),
    ]
