# Generated by Django 2.0.6 on 2019-05-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_panel', '0017_auto_20190520_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletable',
            name='recipe_procedure',
        ),
    ]
